### PR TITLE
Update parts.py

### PR DESCRIPTION
**Pull request by antaares**
Fixed bug in paginate function. 
# Description

The previous code was not working.
I tried this code and it works fine.

- I have performed a self-review of my own code
- My changes are compatible with minimum requirements of the project

### CODE REVIEW

**Review by evgfilim1 — CHANGES_REQUESTED** [review]
This was not a bug. Now you have introduced a magic constant and a breaking change. What is "4" in range? Why cannot I change it to anything I like? Why have you removed "page" argument?

**Comment by antaares** [comment]
Sorry, I wrote another code. I am sorry.

Why do we need a page if we have a limit?

**Comment by evgfilim1** [comment]
> Why do we need a page if we have a limit?

Because `paginate` shouldn't return entire list sliced by `len(part) == limit`. It should return only specific page because it's the only thing you need while paginating.

**Comment by antaares** [comment]
Ehhh, I see now, sorry for taking up your time.

**Pull request closed without merging**
