### PR TITLE
3.x Bot API 6.1

### LINKED ISSUE #936: Bot API 6.1
https://core.telegram.org/bots/api-changelog#june-20-2022

### PR DESCRIPTION
**Pull request by JrooTJunior**
# Description

Added full support of [Bot API 6.1](https://core.telegram.org/bots/api-changelog#june-20-2022)

Fixes #936 

## Type of change

Please delete options that are not relevant.

- [x] Documentation (typos, code examples or any documentation update)
- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by evgfilim1** [comment]
### Join Requests & Payments

- [x] Added the fields `join_to_send_messages` and `join_by_request` to the class [`Chat`](https://core.telegram.org/bots/api#chat).
- [ ] Added the ability to process join requests which were created [without an invite link](https://telegram.org/blog/700-million-and-premium#join-requests-for-public-groups). Bots will receive a “`chat_join_request`” update as usual. _(is request link optional in received class?)_
- [x] Added the method [`createInvoiceLink`](https://core.telegram.org/bots/api#createinvoicelink) to generate an HTTP link for an invoice.

### Telegram Premium Support ([more info](https://telegram.org/blog/700-million-and-premium#telegram-premium))

- [x] Added the field `is_premium` to the class [`User`](https://core.telegram.org/bots/api#user).
- [x] Added the field `premium_animation` to the class [`Sticker`](https://core.telegram.org/bots/api#sticker).

### Attachment Menu Integration

- [x] Added the field `added_to_attachment_menu` to the class [`User`](https://core.telegram.org/bots/api#user).
- [ ] Added support for t.me links that can be used to select the chat in which the attachment menu with the bot will be opened. _(need helper?)_

### Other Changes

- [x] Added the parameter secret_token to the method [`setWebhook`](https://core.telegram.org/bots/api#setwebhook).
- [ ] As previously announced, only HTTPS links are now allowed in `login_url` inline keyboard buttons. _(need check?)_

**Comment by JrooTJunior** [comment]
> Added the ability to process join requests which were created [without an invite link](https://telegram.org/blog/700-million-and-premium#join-requests-for-public-groups). Bots will receive a “chat_join_request” update as usual. (is request link optional in received class?)

Docs: 
`invite_link`	[ChatInviteLink](https://core.telegram.org/bots/api#chatinvitelink)	**Optional.** Chat invite link that was used by the user to send the join request

---

> Added support for t.me links that can be used to select the chat in which the attachment menu with the bot will be opened. (need helper?)

Did you mean the link generator?

---

> As previously announced, only HTTPS links are now allowed in `login_url` inline keyboard buttons. _(need check?)_

We don't validate protocol, is not needed to make additional changes in framework

**Comment by evgfilim1** [comment]
> > Added the ability to process join requests which were created [without an invite link](https://telegram.org/blog/700-million-and-premium#join-requests-for-public-groups). Bots will receive a “chat_join_request” update as usual. (is request link optional in received class?)
> 
> Docs: `invite_link` [ChatInviteLink](https://core.telegram.org/bots/api#chatinvitelink) **Optional.** Chat invite link that was used by the user to send the join request


Yeah, just wanted to make sure it's correct.
https://github.com/aiogram/aiogram/blob/247ffbef69360235239d4eea486494acd2dd3291/aiogram/types/chat_join_request.py#L34

> > Added support for t.me links that can be used to select the chat in which the attachment menu with the bot will be opened. (need helper?)
> 
> Did you mean the link generator?

Yes. Do we need it?

> > As previously announced, only HTTPS links are now allowed in `login_url` inline keyboard buttons. _(need check?)_
> 
> We don't validate protocol, is not needed to make additional changes in framework

Ok, got it.

**Comment by JrooTJunior** [comment]
> > > Added support for t.me links that can be used to select the chat in which the attachment menu with the bot will be opened. (need helper?)
> > 
> > 
> > Did you mean the link generator?
> 
> Yes. Do we need it?

Hm, it can be useful

**Pull request merged**
