### PR TITLE
Bot API v5.6 support

### LINKED ISSUE #800: Add support for Bot API 5.6
- Improved support for Protected Content.
- Added the parameter protect_content to the methods sendMessage, sendPhoto, sendVideo, sendAnimation, sendAudio, sendDocument, sendSticker, sendVideoNote, sendVoice, sendLocation, sendVenue, sendContact, sendPoll, sendDice, sendInvoice, sendGame, sendMediaGroup, copyMessage, forwardMessage to allow sending messages with protected content to any chat.
- Added support for spoiler entities, which will work in Telegram versions released after December 30, 2021. Older clients will display unsupported message.
- Added new MessageEntity type “spoiler”.
- Added the ability to specify spoiler entities using HTML and MarkdownV2 formatting options.

https://core.telegram.org/bots/update56kabdkb12ibuisabdubodbasbdaosd

### PR DESCRIPTION
**Pull request by Olegt0rr**
# Description

Fixes #800

## Type of change
- [x] Documentation (typos, code examples or any documentation update)
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by gabbhack — APPROVED** [review]

**Review by evgfilim1 — CHANGES_REQUESTED** [review]
Looks good, but I think it's better to follow previous version style.

**Review by evgfilim1 — APPROVED** [review]
LGTM, thanks for your effort

**Comment by MasterGroosha** [comment]
Also `<tg-spoiler>xxx</tg-spoiler>` tags work on Production Bot API (maybe not on Local Bot API), so it's worth adding tests for this tag too.

**Comment by Olegt0rr** [comment]
@MasterGroosha, <tg-spoiler> is not used in tag builder, so it's not a problem :)

**Pull request merged**
