### PR TITLE
Add new exceptions in exceptions.py

### PR DESCRIPTION
**Pull request by andrew000**
New exceptions:
* `NoRightsToSendMessage`
* `ChatRestricted`
* `ChannelPrivate`
* `GroupDeleted`
* `NotMemberOfSupergroup`

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by darksidecat** [comment]
Associated with https://github.com/aiogram/aiogram/issues/559

**Comment by JrooTJunior** [comment]
Can you add other errors from #559?

**Comment by andrew000** [comment]
> Can you add other errors from #559?

I have not investigated the errors from #599, so I will not be able to write them down correctly in the PR.

Later I will refactor all exceptions in exceptions.py

**Comment by evgfilim1** [comment]
@andrew000 Any updates?

**Comment by andrew000** [comment]
> @andrew000 Any updates? @JrooTJunior Do we really need this patch? In 3.0 we decided not to split exceptions by their descriptions as they aren't reliable.

I think this PR may be closed. 

Until Telegram makes a list of all possible exceptions (and most likely they won’t) - I think it’s pointless now to catch them at random and try to classify.

**Pull request closed without merging**
