### PR TITLE
Add currency enum

### PR DESCRIPTION
**Pull request by dsodx**
# Description

I added Currency enum.
I believe that my PR will be useful, for example, when creating a payment:
```python
from aiogram.enum import Currency

await bot.send_invoice(
    ...,
    currency=Currency.USD,
    ...
)
```
Since it excludes, above all, typos.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- [x] Test A: `pytest tests` [OK]

- [x] Test B: [OK]
```python
from aiogram.enum import Currency

print(Currency.USD, Currency.EUR)
```
Output:
```shell
USD EUR
```

**Test Configuration**:
* Operating System: `Windows 11 22H2`
* Python version: `3.11.3`

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by JrooTJunior** [comment]
Is it possible to parse the values ​​for this list using Butcher?

**Comment by dsodx** [comment]
Do you mean automatically add new currencies?

**Comment by dsodx** [comment]
@JrooTJunior

**Comment by JrooTJunior** [comment]
Yes.

**Comment by dsodx** [comment]
I think that for now you can leave it as it is, but in the future I may come up with something :).

**Comment by JrooTJunior** [comment]
Please add file `.butcher/enums/Currency.yml` with content described in this comment and then execute command `butcher apply enum` (butcher should be installed with extra `dev` dependencies) and then commit new generated files to the repository.

```yaml
name: Currency
description: |
  Currencies supported by Telegram Bot API

  Source: https://core.telegram.org/bots/payments#supported-currencies

static:
  AED: "AED"  # United Arab Emirates Dirham
  AFN: "AFN"  # Afghan Afghani
  ALL: "ALL"  # Albanian Lek
  AMD: "AMD"  # Armenian Dram
  ARS: "ARS"  # Argentine Peso
  AUD: "AUD"  # Australian Dollar
  AZN: "AZN"  # Azerbaijani Manat
  BAM: "BAM"  # Bosnia & Herzegovina Convertible Mark
  BDT: "BDT"  # Bangladeshi Taka
  BGN: "BGN"  # Bulgarian Lev
  BND: "BND"  # Brunei Dollar
  BOB: "BOB"  # Bolivian Boliviano
  BRL: "BRL"  # Brazilian Real
  BYN: "BYN"  # Belarusian ruble
  CAD: "CAD"  # Canadian Dollar
  CHF: "CHF"  # Swiss Franc
  CLP: "CLP"  # Chilean Peso
  CNY: "CNY"  # Chinese Renminbi Yuan
  COP: "COP"  # Colombian Peso
  CRC: "CRC"  # Costa Rican Colón
  CZK: "CZK"  # Czech Koruna
  DKK: "DKK"  # Danish Krone
  DOP: "DOP"  # Dominican Peso
  DZD: "DZD"  # Algerian Dinar
  EGP: "EGP"  # Egyptian Pound
  ETB: "ETB"  # Ethiopian Birr
  EUR: "EUR"  # Euro
  GBP: "GBP"  # British Pound
  GEL: "GEL"  # Georgian Lari
  GTQ: "GTQ"  # Guatemalan Quetzal
  HKD: "HKD"  # Hong Kong Dollar
  HNL: "HNL"  # Honduran Lempira
  HRK: "HRK"  # Croatian Kuna
  HUF: "HUF"  # Hungarian Forint
  IDR: "IDR"  # Indonesian Rupiah
  ILS: "ILS"  # Israeli New Sheqel
  INR: "INR"  # Indian Rupee
  ISK: "ISK"  # Icelandic Króna
  JMD: "JMD"  # Jamaican Dollar
  JPY: "JPY"  # Japanese Yen
  KES: "KES"  # Kenyan Shilling
  KGS: "KGS"  # Kyrgyzstani Som
  KRW: "KRW"  # South Korean Won
  KZT: "KZT"  # Kazakhstani Tenge
  LBP: "LBP"  # Lebanese Pound
  LKR: "LKR"  # Sri Lankan Rupee
  MAD: "MAD"  # Moroccan Dirham
  MDL: "MDL"  # Moldovan Leu
  MNT: "MNT"  # Mongolian Tögrög
  MUR: "MUR"  # Mauritian Rupee
  MVR: "MVR"  # Maldivian Rufiyaa
  MXN: "MXN"  # Mexican Peso
  MYR: "MYR"  # Malaysian Ringgit
  MZN: "MZN"  # Mozambican Metical
  NGN: "NGN"  # Nigerian Naira
  NIO: "NIO"  # Nicaraguan Córdoba
  NOK: "NOK"  # Norwegian Krone
  NPR: "NPR"  # Nepalese Rupee
  NZD: "NZD"  # New Zealand Dollar
  PAB: "PAB"  # Panamanian Balboa
  PEN: "PEN"  # Peruvian Nuevo Sol
  PHP: "PHP"  # Philippine Peso
  PKR: "PKR"  # Pakistani Rupee
  PLN: "PLN"  # Polish Złoty
  PYG: "PYG"  # Paraguayan Guaraní
  QAR: "QAR"  # Qatari Riyal
  RON: "RON"  # Romanian Leu
  RSD: "RSD"  # Serbian Dinar
  RUB: "RUB"  # Russian Ruble
  SAR: "SAR"  # Saudi Riyal
  SEK: "SEK"  # Swedish Krona
  SGD: "SGD"  # Singapore Dollar
  THB: "THB"  # Thai Baht
  TJS: "TJS"  # Tajikistani Somoni
  TRY: "TRY"  # Turkish Lira
  TTD: "TTD"  # Trinidad and Tobago Dollar
  TWD: "TWD"  # New Taiwan Dollar
  TZS: "TZS"  # Tanzanian Shilling
  UAH: "UAH"  # Ukrainian Hryvnia
  UGX: "UGX"  # Ugandan Shilling
  USD: "USD"  # United States Dollar
  UYU: "UYU"  # Uruguayan Peso
  UZS: "UZS"  # Uzbekistani Som
  VND: "VND"  # Vietnamese Đồng
  YER: "YER"  # Yemeni Rial
  ZAR: "ZAR"  # South African Rand

```

**Comment by Olegt0rr** [comment]
It would be nice to generate full objects with title and amount constraints. Not only ENUM

**Comment by dsodx** [comment]
but the range of values ​​depends on the dollar exchange rate and is constantly changing.

**Comment by Olegt0rr** [comment]
Agree, but the title may help to print the list of choice to user

**Comment by dsodx** [comment]
imho in this case it would be better to make sure that the name of the enum element is also their value

**Review by JrooTJunior — APPROVED** [review]

**Review by JrooTJunior — APPROVED** [review]

**Comment by dsodx** [comment]
@JrooTJunior im sorry, there is an error in my example - can you replace `aiogram.enum` with `aiogram.enums`?

**Comment by JrooTJunior** [comment]
@dsodx, fixed in b9abf701

**Pull request merged**
