### PR TITLE
fix: use default preview options for inline queries

### LINKED ISSUE #1543: Inline queries not respecting bot's default link preview settings
### Checklist

- [X] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### Operating system

Ubuntu 22.04.3 LTS

### Python version

3.11.9

### aiogram version

3.10.0

### Expected behavior

Inline queries should use the bot's default link preview options when sending text messages, maintaining consistency with other message types.

### Current behavior

Currently, inline queries are not using the bot's default link preview options when sending messages. This inconsistency can lead to unexpected behavior and confusion for bot developers and users.

### Steps to reproduce

1. Set up a bot with default link preview options.
2. Implement an inline query handler that returns text messages.
3. Trigger an inline query that results in a text message.
4. Observe that the sent message does not respect the bot's default link preview settings.

### Code example

```python3
import asyncio

from aiogram import Bot, Dispatcher, types
from aiogram.client.default import DefaultBotProperties

bot = Bot(
    token="token",
    default=DefaultBotProperties(
        link_preview_is_disabled=True,
    ),
)

dp = Dispatcher()


@dp.inline_query()
async def inline_query_handler(inline_query: types.InlineQuery):
    await inline_query.answer(
        results=[
            types.InlineQueryResultArticle(
                id="1",
                title="hello",
                description="aiogram",
                input_message_content=types.InputTextMessageContent(
                    message_text="https://github.com/aiogram/aiogram",
                ),
            )
        ],
        cache_time=0,
    )


asyncio.run(dp.start_polling(bot))
```

### Logs

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by chuangbo**
Improve `link_preview_options` parameter in `InputTextMessageContent` class:
- Add default value `Default("link_preview")`
- Change default key from `disable_web_page_preview` to `link_preview_is_disabled` to match `DefaultBotProperties` definition

This allows inline query handlers to use bot's default link preview options.

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

Fixes #1543 

## Type of change

Please delete options that are not relevant.

- [ ] Documentation (typos, code examples or any documentation update)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

```python
import asyncio

from aiogram import Bot, Dispatcher, types
from aiogram.client.default import DefaultBotProperties

bot = Bot(
    token="token",
    default=DefaultBotProperties(
        link_preview_is_disabled=True,
    ),
)

dp = Dispatcher()


@dp.inline_query()
async def inline_query_handler(inline_query: types.InlineQuery):
    await inline_query.answer(
        results=[
            types.InlineQueryResultArticle(
                id="1",
                title="hello",
                description="aiogram",
                input_message_content=types.InputTextMessageContent(
                    message_text="https://github.com/aiogram/aiogram",
                ),
            )
        ],
        cache_time=0,
    )


asyncio.run(dp.start_polling(bot))

```

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Operating System: macOS 14.5
* Python version: 3.11.9

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by JrooTJunior** [comment]
Thanks for your contribution, but any type or method properties should not be edited manually because of code generation, they should be changed in code generation configurations and then reflected using a utility that is only available to aiogram core developers.

I will do it later.

Also, note that the `disable_web_page_preview` option is deprecated in the Bot API, `link_preview_options` should be used instead, so take that into account in your code: https://core.telegram.org/bots/api#linkpreviewoptions

**Comment by chuangbo** [comment]
I understand now. Should I update the `.butcher/types/InputTextMessageContent/default.yml` file instead?

**Comment by JrooTJunior** [comment]
Yes, but you can't regenerate the code after it because the codegen utility isn't currently open.

Also, I see that this property was missing by default for some other types, so I'll fix that soon.

**Comment by chuangbo** [comment]
Love you ❤️

**Pull request closed without merging**
