### PR TITLE
Project typos fix

### PR DESCRIPTION
**Pull request by barbashovtd**

### CODE REVIEW

**Review by Olegt0rr — APPROVED** [review]

**Review by Olegt0rr — CHANGES_REQUESTED** [review]
Let's change it to `The field contains a list of objects`

**Comment by Olegt0rr** [comment]
Also, if you want to correct typos, check the entire file (you will definitely find other typos)

**Comment by Olegt0rr** [comment]
> Also, if you want to correct typos, check the entire file (you will definitely find other typos)

@barbashovtd,
Still actual. Please, fix all typos in the file.

**Comment by barbashovtd** [comment]
Sorry for trash - did not sleep, inattentive.
Also I find typo in _dispatcher/filters/state.py: StatesGroupMeta_ - field named childs, right name - children. Decided not to touch it as don`t know how necessary it is.
---
Извиняюсь за ужасные коммиты. Также нашёл неверный перевод в dispatcher/filters/state.py: StatesGroupMeta: поле childs корректнее назвать children. Решил не трогать, так как не знаю насколько критично, и вроде глубоко в проекте сидит.

**Review by evgfilim1 — APPROVED** [review]
Looks good, thanks for PR!
However, you were requested to check typos in other files, so it'd be really better to fix them too, if any.

**Review by Olegt0rr — APPROVED** [review]

**Review by JrooTJunior — APPROVED** [review]

**Pull request merged**
