### PR TITLE
Adding new code-generator (Butcher)

### PR DESCRIPTION
**Pull request by JrooTJunior**
# Description

Added integration with new code-generator named Butcher: https://github.com/aiogram/butcher

## Type of change

- Documentation (typos, code examples or any documentation update)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have added tests that prove my fix is effective or that my feature works as expected
- [x] New and existing unit tests pass locally with my changes
- [x] My changes generate no new warnings or errors
- [x] My changes are compatible with minimum requirements of the project
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by torikki-tou** [comment]
https://github.com/aiogram/butcher is 404 now, is it publicly available?

**Comment by JrooTJunior** [comment]
It is hidden from public access, accessible only to the development team.

**Comment by torikki-tou** [comment]
sad to hear, any plans to opensource?

**Comment by JrooTJunior** [comment]
Maybe in the future, but definitely not in the near future.

**Pull request merged**
