### PR TITLE
Update echo_bot.py

### PR DESCRIPTION
**Pull request by arynyklas**
# Description

Deleted unnecessary parts about cats and /start command.

Fixes # (issue)

## Type of change

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by evgfilim1 — CHANGES_REQUESTED** [review]
You've just deleted a lot of code without motivating it in any way...

**Comment by arynyklas** [comment]
> You've just deleted a lot of code without motivating it in any way...

I deleted unnecessary parts.

**Comment by evgfilim1** [comment]
> > You've just deleted a lot of code without motivating it in any way...
> 
> I deleted unnecessary parts.

@arynyklas why do you think they're unnecessary? IMHO, echo bot shouldn't be a simple and stupid bot which just echos messages, it should do smth else.

**Comment by arynyklas** [comment]
> > > You've just deleted a lot of code without motivating it in any way...
> > 
> > 
> > I deleted unnecessary parts.
> 
> @arynyklas why do you think they're unnecessary? IMHO, echo bot shouldn't be a simple and stupid bot which just echos messages, it should do smth else.

Why not? It's stupid to do something else that doesn't concern echo-bot.

**Comment by JrooTJunior** [comment]
@arynyklas 
> Why not? It's stupid to do something else that doesn't concern echo-bot.

Don't be rude, but please just explain in detail why these changes should be approved?

This example committed on May 27, 2017 https://github.com/aiogram/aiogram/commit/2fdd804114f1e6d9e2d26f27ac6c38333dbc01ba before first release of the framework and i don't see any reasons to change this example in 2.x branch.

**Comment by evgfilim1** [comment]
I agree with @JrooTJunior.

If you'd like to improve echo bot, this can be done in many ways like
- adding inline echo part
- making it echo every type of messages, not only text ones
- covering it with tests, adding ci/cd and smth like this

But you just deleted "useless" part with cats and /start not even deleting those cats from repo.

**Pull request closed without merging**
