### PR TITLE
update workflow data

### PR DESCRIPTION
**Pull request by sheldygg**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Documentation (typos, code examples or any documentation update)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Operating System:
* Python version:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Olegt0rr** [comment]
@sheldygg what's the issue? It works the same, it seems

**Comment by sheldygg** [comment]
> @sheldygg what's the issue? It works the same, it seems

not the same
when i pass kwargs to `start_polling` method they are not added to workflow_data

MRE
```python
import asyncio

from aiogram import Bot, Dispatcher
from aiogram.filters import CommandStart
from aiogram.types import Message

TOKEN = ""
dp = Dispatcher()


@dp.message(CommandStart())
async def command_start_handler(message: Message, some_val: str) -> None:
    assert dp.workflow_data.get("some_val") is not None
    await message.answer(some_val)


async def main() -> None:
    bot = Bot(TOKEN)
    await dp.start_polling(bot, some_val="ok")


if __name__ == "__main__":
    asyncio.run(main())
```

**Comment by JrooTJunior** [comment]
I don't quite understand why it should be added to `workflow_data`.

You should not access `dispatcher.workflow_data` directly from handlers, as you can always retrieve data from it via handler arguments.

**Comment by sheldygg** [comment]
> I don't quite understand why it should be added to `workflow_data`.
> 
> You should not access `dispatcher.workflow_data` directly from handlers, as you can always retrieve data from it via handler arguments.
> 
> Why `start_polling` should modify `workflow_data`?

usually the parameters i need i pass to `Dispatcher.start_polling` kwargs, then i can get it as handler argument

i my case i use `Dispatcher.feed_update` and i must pass all parameters which i already pass to `Dispatcher.start_polling` otherwise i will get something like that `missing 1 required positional argument: 'some_val'`.

to avoid this, I suggest updating the workflow_data so that it can be used like this
`dp.feed_update(bot=bot, update=update, **dp.workflow_data)`

**Pull request closed without merging**
