### PR TITLE
GitHub Action to run pre-commit

### PR DESCRIPTION
**Pull request by cclauss**
# Description

Results: https://github.com/cclauss/aiogram/actions

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Documentation (typos, code examples or any documentation update)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Operating System: 
* Python version: 

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by JrooTJunior** [comment]
Why do you add new action?
black, isort, flake8, mypy checks is already used at build action directly check on multiple platforms.

I don't see any reasons to add one more action with the same scenario

**Comment by cclauss** [comment]
black, isort, flake8, mypy Do not need to be run on multiple operating systems because they will provide identical results.  So running them once in a quick job provides rapid feedback to contributors who have not yet configured pre-commit on their local machines.  This moves configuration complexity out of GitHub Actions so our non-pre-commit jobs will run faster and in parallel.

**Comment by JrooTJunior** [comment]
It's wrong because new versions of Python has changes in syntax and code should be checked for each supported version

**Comment by JrooTJunior** [comment]
And now after you changed the action with using the matrix build, why we need to provide two separate actions with the same functionality?

**Comment by JrooTJunior** [comment]
So.. As the result..
I dont like `pre-commit` util because in the past it doesn't works correctly with customized black, isort, mypy configs and also it doesn't respect the `dependencies`/`dev-dependencies` section of `pyproject.toml` and can use different version of required `black`, `isort`, `flake8`, `mypy` i won't to use only `pre-commit` to run checks in my projects, i'll recommend you to add step with `pre-commit` to `tests.yml` action as new step without replacion old ones. In this case we have directly call to the linters and then run `pre-commit` with additional check, when something wrong with version or configs we can always see the source of this errors.

**Pull request closed without merging**
