### PR TITLE
Mongo storage

### PR DESCRIPTION
**Pull request by Olegt0rr**
# Description
Added Mongo storage support based on [aiomongo](https://github.com/ZeoAlliance/aiomongo)

### CODE REVIEW

**Comment by Birdi7** [comment]
Last commit is 2 year ago at [aiomongo](https://github.com/ZeoAlliance/aiomongo). Is this fine?

**Comment by JrooTJunior** [comment]
Is [Motor](https://motor.readthedocs.io/en/stable/) has the same interface? Maybe this storage can be maked more universally for usage with different drivers. Or maybe can be splitted into different storages like `MotorsMongoStorage` and `AioMongoStorage`.

Because Motor looks more reliable

**Comment by Olegt0rr** [comment]
> Last commit is 2 year ago at [aiomongo](https://github.com/ZeoAlliance/aiomongo). Is this fine?

Not aiomongo works fine and it's enought for me.
I'm not sure about motor speed. 2 years ago aiomongo was more faster than motor (look at the benchmarks).

If you can make fresh comparison of motor and aiomongo - please, do it.

**Comment by JrooTJunior** [comment]
I'll merge this PR but after that i rename module from mongo to aiomongo and after that add the motor version of this storage because Motor is official library and is more popular

**Pull request merged**
