### PR TITLE
doc added for missing Telegram WebApp API classes and fields

### PR DESCRIPTION
**Pull request by Leroy-bit**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ x ] Documentation (typos, code examples or any documentation update)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Operating System:
* Python version:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ x ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Latand** [comment]
Hello, @Leroy-bit 

Thank you for the effort you've put into updating the translations for the project.

I noticed that the translations for the Ukrainian documentation have been updated in your PR. However, it seems that the primary English documentation hasn't been updated yet. Typically, we should update the English version first to reflect the most recent changes, as it serves as the base for all translations.

Could you please check and confirm if the English documentation is up-to-date with the changes that you've translated? If not, I would recommend updating the English documentation first and then aligning the translation to match it.

**Comment by Latand** [comment]
You can read about how to compile and update the docs [in this section ](https://docs.aiogram.dev/en/latest/contributing.html#docs)

**Comment by Leroy-bit** [comment]
> Could you please check and confirm if the English documentation is up-to-date with the changes that you've translated? If not, I would recommend updating the English documentation first and then aligning the translation to match it.

@Latand I did according to the docs contibution instructions. I added autoclass to the web_app.rst file, then compiled it with phoenix to babel. On local machine all changes are displayed correctly.

**Comment by Latand** [comment]
I see, there is an autoclass function, seems to be it

**Comment by Leroy-bit** [comment]
As i understand autoclass doc texts are not stored directly in documentation files, but in doc strings of class code

**Review by JrooTJunior — APPROVED** [review]

**Pull request merged**
