### PR TITLE
change gender name

### PR DESCRIPTION
**Pull request by yallxe**
There are only 3 genders, intersex people are born with sex characteristics (including genitals, gonads and chromosome patterns) that do not fit typical binary notions of male or female bodies.

# Description

Minor typo fixes and new features to examples

## Type of change

New features

# How Has This Been Tested?
Tested by running a bot and checking all the functionality.

**Test Configuration**:
* Operating System: Windows 10
* Python version: Python 3.9

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Olegt0rr — CHANGES_REQUESTED** [review]
Against!
`Other` includes all other kinds of sex.
Tomorrow somebody can create another one kind of sex...

Rainbow consists of many colours, but in the list we're prefer to name only some of them. The same for the sex.

```python
if somebody.has_a_dick():
    somebody.sex = "Male"
else:
    somebody.sex = "Female"

if somebody.its_complicated():
    somebody.sex = "Other"
```

**Comment by yallxe** [comment]
@Olegt0rr 
Let's be precise. Gender and sex is the same one things. There are a lot of gender **identifications** and only three real **existing** genders.

`Today everybody can create another one kind of sex` 
No. `Today everybody can create another kind of gender identification` will be the true sentence, but gender is not equal gender identification.

Available genders: `Male, Female and Intersex (mixed genitals)`
Available gender identities: `a lot`

**Comment by Olegt0rr** [comment]
`Other` include all of available kind. 
So, intersex users can choose `other`.

**Comment by yallxe** [comment]
But why don't we be precise? It might hurt some people that their gender is marked as `other` at the service.

**Comment by evgfilim1** [comment]
> It might hurt some people that their gender is marked as `other` at the service.

Yes, I agree, it might, but... Isn't it _just an example_ that shows how to use FSM in aiogram? It's _not a real_ service. So, do we really need this enhancement/fix?

**Comment by Olegt0rr** [comment]
> But why don't we be precise? It might hurt some people that their gender is marked as `other` at the service.

`OTHER` is not used to offend, it is a grouping of some cases (including unusual genders, gender identification, gender denial, e.t.c.).
This file created to show an example of using the FSM. 
In your own bot, you can use a list of genders convenient for you.

**Comment by JrooTJunior** [comment]
@yallxe, how adding more genders (or changing existing one) to this example helps explaining FSM feature?

Let's be objective.
Adding more buttons to gender choosing step helps to understanding FSM?
Adding 42 new genders to list helps to avoid insult to the senses other thousands of genders?

Owke, if you want you can change gender choosing step to any other is not related with genders, race or other sensitive themes, but current way (changing other to intersex) is not practical and does't take any positive effects or improvements.

Right?

---

So.. In the fact.. I can approve this pull request **only** if you change this step to other non-sensitive theme instead of renaming current one button.

**Comment by evgfilim1** [comment]
Other possible option discussed in our dev chat is to ask exact gender on "Other" button with ability to click "Prefer not to say". It will be useful to showcase smth like additional (optional) branch in conversation.

**Comment by yallxe** [comment]
@JrooTJunior There is no 42 genders, as I explained there are only 3 real existing genders (which contains differences in genitals).

**Comment by evgfilim1** [comment]
@yallxe, so, this patch is useless, it just changes text on the button in the example. For now, I'll close this PR.
If you want to improve our FSM example somehow, feel free to implement this idea: https://github.com/aiogram/aiogram/pull/613#issuecomment-870448297.

**Pull request closed without merging**
