### PR TITLE
Add MongoStorage for FSM (MongoDB driver)

### PR DESCRIPTION
**Pull request by selfkilla666**
# Description

Adding a new class `aiogram.fsm.storage.MongoStorage` - MongoDB driver for aiogram's Finite State Machine. It works on the base of asynchronous `motor` module to work with MongoDB. Was developed as part of an in-house project, and finalized to add to the aiogram library. Can be used via:
```python
from aiogram import Dispatcher
from aiogram.fsm.storage.mongo import MongoStorage

from motor.motor_asyncio import AsyncIOMotorClient


MONGODB_CLUSTER_URI = environ.get("MONGODB_CLUSTER_URI", "No URL!")

mongo_client: AsyncIOMotorClient = AsyncIOMotorClient(MONGODB_CLUSTER_URI)
mongo_storage: MongoStorage = MongoStorage(mongo_client)
dispatcher: Dispatcher = Dispatcher(storage=mongo_storage)

```
or initialize directly for the URI:
```python
mongo_storage: MongoStorage = MongoStorage.from_url(MONGODB_CLUSTER_URI)
```
Otherwise, the module works like all other FSM-Storage. Documentation and dependency updates are also included.

## Type of change

Please delete options that are not relevant.

- [x] Documentation (typos, code examples or any documentation update)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

This FSM storage module for MongoDB was written for in-house development (bot), and was tested for performance in a business project. Only documentation, dependencies, and black-style code reformatting were added to add it to the standard `aiogram` library. There are no ready unit tests available (yet).

**Test Configuration**:
* Operating System: Windows 10 / Ubuntu 22.04 LTS  

* Python version: 3.12

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

Update: I added a unit test to check MongoStorage and it passes successfully

### CODE REVIEW

**Comment by selfkilla666** [comment]
I added a unit test to check MongoStorage and it passes successfully

**Review by JrooTJunior — CHANGES_REQUESTED** [review]
What about events isolation mechanism based on the Mongo? It can be safely used?

**Comment by JrooTJunior** [comment]
@selfkilla666, any news?

**Comment by JrooTJunior** [comment]
Mongo Storage seems to have been cursed 😞

3 unfinished PR's with this storage implementation.

**Comment by Vadim-Khristenko** [comment]
@JrooTJunior @selfkilla666 
I think that this PR should be closed, since MongoStorage has already been implemented in Aiogram and has been successfully added in version 3.7.0 #1434 
+ There are no updates from the author PR.

**Pull request closed without merging**
