### PR TITLE
Fixed example code indentation in quick_start.rst

### PR DESCRIPTION
**Pull request by paul-nameless**
Fixed example code indentation

### CODE REVIEW

**Comment by JrooTJunior** [comment]
Something strange. Is already fixed in #54 and #45 PR's.

**Comment by paul-nameless** [comment]
Hm, yes it is in dev-2.x branch

**Comment by JrooTJunior** [comment]
Yes, but #54 is already merged with master.

**Comment by JrooTJunior** [comment]
Fixed in `dev-2.x` branch. Will be merged soon.

**Pull request closed without merging**
