### PR TITLE
Fix ChatMemberHandler import in __init__.py

### PR DESCRIPTION
**Pull request by WhiteMemory99**
# Description

The ChatMemberUpdated class is being imported instead of ChatMemberHandler, which is wrong here.

## Type of change

Please delete options that are not relevant.

- [ ] Documentation (typos, code examples or any documentation update)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Operating System: 
* Python version: 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by JrooTJunior — APPROVED** [review]

**Comment by JrooTJunior** [comment]
Can you please try to update your branch with the latest changes of `dev-3.x`?

I'm not sure why tests failed only on Windows with Python 3.9 but now it works in the `dev-3.x` branch.

**Comment by WhiteMemory99** [comment]
> Can you please try to update your branch with the latest changes of `dev-3.x`?
> 
> I'm not sure why tests failed only on Windows with Python 3.9 but now it works in the `dev-3.x` branch.

Done!

**Review by evgfilim1 — APPROVED** [review]
Looks good, thanks for PR!

**Comment by JrooTJunior** [comment]
Perfect

**Pull request merged**
